"""
Audit Trail Validator - Add source verification to Excel cells.

Target Users: Junior Bankers & Associates
"""

from openpyxl import load_workbook
from openpyxl.comments import Comment
from openpyxl.styles import Font, PatternFill
from daloopa_client import DaloopaMCPClient


def verify_source_links(
    model_path: str,
    cell_range: str,
    data_point_mapping: dict,
    mcp_client: DaloopaMCPClient
) -> dict:
    """
    Add source verification comments to Excel cells.

    Args:
        model_path: Path to Excel file
        cell_range: Range to verify (e.g., "B10:B50")
        data_point_mapping: Dict mapping cells to data_point_ids
        mcp_client: Daloopa MCP client instance

    Returns:
        dict with verification summary
    """
    wb = load_workbook(model_path)
    sheet = wb.active

    results = {
        "verified_cells": [],
        "unverified_cells": [],
        "sources": []
    }

    # Parse range
    start_cell, end_cell = cell_range.split(':')
    col = start_cell[0]
    start_row = int(start_cell[1:])
    end_row = int(end_cell[1:])

    for row in range(start_row, end_row + 1):
        cell_ref = f"{col}{row}"
        cell = sheet[cell_ref]

        # Skip empty cells
        if cell.value is None:
            continue

        # Get data point ID for this cell
        data_point_id = data_point_mapping.get(cell_ref)

        if not data_point_id:
            results["unverified_cells"].append(cell_ref)
            # Mark unverified cells with light red
            cell.fill = PatternFill('solid', start_color='FFE4E1')
            continue

        # Fetch source context from Daloopa
        source = mcp_client.get_source_context(data_point_id)

        # Build and add comment
        comment_text = build_source_comment(source)
        cell.comment = Comment(comment_text, "Daloopa Audit")
        cell.comment.width = 400
        cell.comment.height = 150

        # Mark as verified with light green
        cell.fill = PatternFill('solid', start_color='E8F5E9')

        results["verified_cells"].append(cell_ref)
        results["sources"].append({
            "cell": cell_ref,
            "value": cell.value,
            "source_type": source["source_type"],
            "filing_date": source["filing_date"],
            "page": source["page_number"],
            "url": source["pdf_url"],
            "sec_url": source.get("sec_url", "")
        })

    # Create audit trail sheet
    create_audit_sheet(wb, results["sources"])

    wb.save(model_path)

    return {
        "file": model_path,
        "range": cell_range,
        "total_cells": end_row - start_row + 1,
        "verified": len(results["verified_cells"]),
        "unverified": len(results["unverified_cells"]),
        "audit_sheet_created": True,
        "sources": results["sources"]
    }


def build_source_comment(source: dict) -> str:
    """Build formatted comment text from source context."""
    snippet = source.get('text_snippet', '')
    if len(snippet) > 200:
        snippet = snippet[:200] + "..."

    lines = [
        f"SOURCE VERIFICATION",
        f"-------------------",
        f"Type: {source['source_type']}",
        f"Filed: {source['filing_date']}",
        f"Page: {source['page_number']}",
        "",
        f"Snippet: \"{snippet}\"",
        "",
        f"Daloopa: {source['pdf_url']}",
        f"SEC: {source.get('sec_url', 'N/A')}"
    ]
    return "\n".join(lines)


def create_audit_sheet(wb, sources: list):
    """Create or update the Audit Trail sheet."""
    # Remove existing audit sheet if present
    if "Audit Trail" in wb.sheetnames:
        del wb["Audit Trail"]

    ws_audit = wb.create_sheet("Audit Trail")

    # Title
    ws_audit['A1'] = "Data Source Audit Trail"
    ws_audit['A1'].font = Font(bold=True, size=14)
    ws_audit.merge_cells('A1:F1')

    ws_audit['A2'] = "Generated by Daloopa MCP"
    ws_audit['A2'].font = Font(italic=True, size=9)

    # Headers
    headers = ["Cell", "Value", "Source Type", "Filing Date", "Page", "PDF URL"]
    for col_idx, header in enumerate(headers, 1):
        cell = ws_audit.cell(row=4, column=col_idx, value=header)
        cell.font = Font(bold=True)
        cell.fill = PatternFill('solid', start_color='D9E1F2')

    # Data
    for row_idx, source_data in enumerate(sources, 5):
        ws_audit.cell(row=row_idx, column=1, value=source_data["cell"])
        ws_audit.cell(row=row_idx, column=2, value=source_data["value"])
        ws_audit.cell(row=row_idx, column=3, value=source_data["source_type"])
        ws_audit.cell(row=row_idx, column=4, value=source_data["filing_date"])
        ws_audit.cell(row=row_idx, column=5, value=source_data["page"])

        # Make URL clickable
        url_cell = ws_audit.cell(row=row_idx, column=6, value=source_data["url"])
        url_cell.hyperlink = source_data["url"]
        url_cell.font = Font(color="0000FF", underline="single")

    # Column widths
    ws_audit.column_dimensions['A'].width = 8
    ws_audit.column_dimensions['B'].width = 15
    ws_audit.column_dimensions['C'].width = 12
    ws_audit.column_dimensions['D'].width = 12
    ws_audit.column_dimensions['E'].width = 8
    ws_audit.column_dimensions['F'].width = 50

    # Summary
    summary_row = len(sources) + 7
    ws_audit.cell(row=summary_row, column=1, value="Summary").font = Font(bold=True)
    ws_audit.cell(row=summary_row + 1, column=1, value=f"Total cells verified: {len(sources)}")

    # Source type breakdown
    source_types = {}
    for s in sources:
        st = s["source_type"]
        source_types[st] = source_types.get(st, 0) + 1

    for i, (st, count) in enumerate(source_types.items()):
        ws_audit.cell(row=summary_row + 2 + i, column=1, value=f"{st}: {count}")


def auto_verify_daloopa_cells(
    model_path: str,
    mcp_client: DaloopaMCPClient
) -> dict:
    """
    Automatically find and verify all Daloopa-sourced cells.

    Looks for cells with Daloopa metadata stored in a hidden mapping sheet.

    Args:
        model_path: Path to Excel file
        mcp_client: Daloopa MCP client

    Returns:
        dict with verification results
    """
    wb = load_workbook(model_path)

    # Check for mapping sheet
    if "_daloopa_mapping" not in wb.sheetnames:
        return {"error": "No Daloopa mapping found. Use verify_source_links with explicit mapping."}

    mapping_sheet = wb["_daloopa_mapping"]
    data_point_mapping = {}

    for row in range(2, mapping_sheet.max_row + 1):
        cell_ref = mapping_sheet.cell(row=row, column=1).value
        dp_id = mapping_sheet.cell(row=row, column=2).value
        if cell_ref and dp_id:
            data_point_mapping[cell_ref] = dp_id

    wb.close()

    if not data_point_mapping:
        return {"error": "Mapping sheet is empty"}

    # Find range from mapping
    cells = list(data_point_mapping.keys())
    cols = set(c[0] for c in cells)

    results = []
    for col in cols:
        col_cells = [c for c in cells if c[0] == col]
        col_rows = sorted([int(c[1:]) for c in col_cells])
        cell_range = f"{col}{col_rows[0]}:{col}{col_rows[-1]}"

        result = verify_source_links(
            model_path, cell_range, data_point_mapping, mcp_client
        )
        results.append(result)

    return {
        "file": model_path,
        "columns_verified": len(results),
        "results": results
    }


def create_mapping_from_kpi_response(
    response: dict,
    start_cell: str
) -> dict:
    """
    Create a data point mapping from a Daloopa KPI response.

    Args:
        response: Response from get_kpi_time_series
        start_cell: Starting cell (e.g., "B10")

    Returns:
        dict: Mapping of cells to data_point_ids
    """
    mapping = {}

    col = start_cell[0]
    start_row = int(start_cell[1:])

    periods = response.get("periods", [])
    for i, period in enumerate(periods):
        cell_ref = f"{col}{start_row + i}"
        mapping[cell_ref] = period.get("data_point_id")

    return mapping


def generate_verification_report(results: dict) -> str:
    """
    Generate a text summary of verification results.

    Args:
        results: Results from verify_source_links

    Returns:
        str: Formatted report text
    """
    lines = [
        "=" * 50,
        "DALOOPA AUDIT TRAIL VERIFICATION REPORT",
        "=" * 50,
        "",
        f"File: {results['file']}",
        f"Range: {results['range']}",
        "",
        f"Total cells: {results['total_cells']}",
        f"Verified: {results['verified']}",
        f"Unverified: {results['unverified']}",
        "",
        "Source Breakdown:",
    ]

    # Count by source type
    source_types = {}
    for s in results.get("sources", []):
        st = s["source_type"]
        source_types[st] = source_types.get(st, 0) + 1

    for st, count in source_types.items():
        lines.append(f"  - {st}: {count}")

    lines.extend([
        "",
        "Verified Cells:",
    ])

    for source in results.get("sources", []):
        lines.append(f"  {source['cell']}: {source['value']} ({source['source_type']} p.{source['page']})")

    if results['unverified'] > 0:
        lines.extend([
            "",
            "WARNING: Unverified cells should be manually checked.",
        ])

    return "\n".join(lines)


if __name__ == "__main__":
    # Example usage
    client = DaloopaMCPClient()

    # Example mapping (in practice, this comes from earlier data fetches)
    mapping = {
        "B10": "dp_DASH_Revenue_Q1_2024",
        "B11": "dp_DASH_Revenue_Q2_2024",
        "B12": "dp_DASH_Revenue_Q3_2024",
        "B13": "dp_DASH_Revenue_Q4_2024"
    }

    result = verify_source_links(
        model_path="sample_model.xlsx",
        cell_range="B10:B13",
        data_point_mapping=mapping,
        mcp_client=client
    )

    print(generate_verification_report(result))
